version: 0.2

phases:
  install:
    runtime-versions:
       ruby: 3.0
    commands:
      - echo "Installing Bundler..."
      - gem install bundler 
      - bundle install
  pre-build:
    commands:
      - echo "Preparing database to run tests..."
      - bundle exec rails db:create RAILS_ENV=test 
      - bundle exec rails db:migrate RAILS_ENV=test # Use bundle exec for rake commands
      - echo "Running tests..."
      - bundle exec rspec spec
  build:
    commands:
      - echo "Build completed successfully!"
      - bundle exec rspec spec

