version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.0
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec rake db:create db:migrate # Or any other necessary build commands
  post_build:
    commands:
      - echo "Build completed successfully!"
  build:
    commands:
      - echo "Running tests..."
      - bundle exec rspec spec