version: 0.2

phases:
  
  pre_build:
    commands:
      - echo "Installing Ruby 3.0..."
      - rbenv  install 3.0.0
      - rbenv global 3.0.0
      - ruby -v 
      - gem install bundler
      - bundle install
  build:
    commands:
      - bundle exec rake db:create db:migrate # Use bundle exec for rake commands
      - echo "Running tests..."
      - bundle exec rspec spec
  post_build:
    commands:
      - echo "Build completed successfully!"
