version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.0
  pre_build:
    commands:
      - echo "Installing Ruby 3.0..."
      # Check if Ruby 3.0 is already installed
      - if ! rbenv versions | grep -q "3.0.0"; then rbenv install 3.0.0; fi
      - rbenv global 3.0.0
      - ruby -v 
      - bundle install
  build:
    commands:
      - bundle exec rake db:create db:migrate # Or any other necessary build commands
  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Running tests..."
      - bundle exec rspec spec
